/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class p2_GUI */

#ifndef _Included_p2_GUI
#define _Included_p2_GUI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     p2_GUI
 * Method:    name
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_p2_1GUI_name
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
