/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_data */

#ifndef _Included_example_data
#define _Included_example_data
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_data
 * Method:    data
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_example_1data_data
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
