/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class p2_IO */

#ifndef _Included_p2_IO
#define _Included_p2_IO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     p2_IO
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_p2_1IO_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     p2_IO
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_p2_1IO_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     p2_IO
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_p2_1IO_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     p2_IO
 * Method:    intArrayMethod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_p2_1IO_intArrayMethod
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     p2_IO
 * Method:    intArray
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_p2_1IO_intArray
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
