/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class p2_IO */

#ifndef _Included_p2_IO
#define _Included_p2_IO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     p2_IO
 * Method:    name
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_p2_1IO_name
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
